<?php
/*
This php script is used to generate the fastestvpn serverlist.
It's using the xml file generated by the windows fastestvpn client.
This fastestvpn client stores the full serverlist in %localappdata%\FastestVPN\local.xml.
This file is read by the below script and it will update the fastestvpn JSON part in storage/servers.json.
*/
$serversjsonfile = "../../storage/servers.json";
$fastestxmlfile = getenv("localappdata") . "/FastestVPN/localdata.xml";

// Read xml file
$xmlraw = file_get_contents($fastestxmlfile);
// Add end of </Settings> which is missing for some reason ?????
$xmlraw .= "\n</Settings> ";
try {
    $xml = simplexml_load_string($xmlraw);
} catch (Exception $e) {
    echo 'xml load error: ',  $e->getMessage(), "\n";
    die("Error get xml info from $fastestxmlfile!\n   Exit!\n");
}
if (!isset($xml->ServerGroups->ServerGroup)) {
    die("No ServerGroup's found in $fastestxmlfile !\n Start FastestVpn App to generate the xml and try again!  Exit!\n");
}

// Read intenal server.json
$serversraw = file_get_contents($serversjsonfile);
$serversjson = json_decode($serversraw, true);
if (count($serversjson) < 1) {
    die("No providers defined in servers.json?  Exit!\n");
}
// Check for fastestvpn existence
if (!isset($serversjson["fastestvpn"])) {
	$serversjson["fastestvpn"] = array();
	$serversjson["fastestvpn"]["version"] = 2;
	$serversjson["fastestvpn"]["timestamp"] = time();
}
if (!isset($serversjson["fastestvpn"]["servers"])) {
	$serversjson["fastestvpn"]["servers"] = array();
}
print("Current Servers.json defined providers:" . count($serversjson) . "  fastestvpn servers:" . count($serversjson["fastestvpn"]["servers"]) . "\n");

// Build an initial Servers Array from the xml entries
$Servers = array();
foreach ($xml->ServerGroups->ServerGroup as $key1 => $xmlvalue) {
    //print_r($key);
    //print_r($xmlvalue);
    foreach ($xmlvalue->Servers as $key2 => $seversvalues) {
        //print_r($seversvalues);
        foreach ($seversvalues as $key3 => $value) {
            if ($value->Active &&
                ("$value->Protocol" == "UDP" || "$value->Protocol" == "TCP" || "$value->Protocol" == "wg")) {
                //print("$xmlvalue->Name : $value->Continent  $value->Country  $value->City  $value->Dns  $value->Ip  $value->Protocol  $value->WgKey\n");
                if (!array_key_exists("$value->Dns", $Servers)) {
                    $Servers["$value->Dns"] = array();
                    $Servers["$value->Dns"]["tcp"] = false ;
                    $Servers["$value->Dns"]["udp"] = false ;
                    $Servers["$value->Dns"]["wgpubkey"] = "";
                }
                $purpose = "normal";
                if ("$xmlvalue->Name" != "Countries") {
                    $purpose = "$xmlvalue->Name";
                }
                $Servers["$value->Dns"]["purpose"] = "$purpose";
                $Servers["$value->Dns"]["continent"] = "$value->Continent";
                $Servers["$value->Dns"]["country"] = "$value->Country";
                $Servers["$value->Dns"]["city"] = "$value->City";
                $Servers["$value->Dns"]["hostname"] = "$value->Dns";
				$Servers["$value->Dns"]["ips"] = array("$value->Ip");
                if ("$value->Protocol" == "TCP") {
                    $Servers["$value->Dns"]["tcp"] = true ;
                }
                if ("$value->Protocol" == "UDP") {
                    $Servers["$value->Dns"]["udp"] = true ;
                }
                if ("$value->WgKey" != "") {
                    $Servers["$value->Dns"]["wgpubkey"] = "$value->WgKey" ;
                }
            }
        }
    }
}

// Sort the servers by hostname
//ksort($Servers);

usort($Servers, function ($item1, $item2) {
    return $item1['country'].$item1['city'] <=> $item2['country'].$item2['city'];
});


// Update the current tree
$serversjson["fastestvpn"]["timestamp"] = time();
print_r($serversjson["fastestvpn"]);
// Start new Serverlist
$serversjson["fastestvpn"]["servers"] = array();
foreach ($Servers as $HostName => $Server) {
    array_push(
        $serversjson["fastestvpn"]["servers"],
        array(
        "vpn" => "openvpn",
        "country" => $Server["country"],
        "city" => $Server["city"],
        "hostname" => $Server["hostname"],
        "tcp" => $Server["tcp"],
        "udp" => $Server["udp"],
        "ips" => $Server["ips"]
        )
    );
    array_push(
        $serversjson["fastestvpn"]["servers"],
        array(
        "vpn" => "wireguard",
        "country" => $Server["country"],
        "city" => $Server["city"],
        "hostname" => $Server["hostname"],
        "wgpubkey" => $Server["wgpubkey"],
        "ips" => $Server["ips"]
        )
    );
}
print("    New Servers.json defined providers:" . count($serversjson) . "  fastestvpn servers:" . count($serversjson["fastestvpn"]["servers"]) . "\n");
file_put_contents($serversjsonfile, json_encode($serversjson, JSON_PRETTY_PRINT));
print("File \"$serversjsonfile updated\".\n");
